This is the fizzbuzz exercise. It does print out the required output.…
unioncollege-webtech/fizzbuzz pull request #21
Opened 2016-09-18 20:32 UTC by mkdev2015

… However, it does not pass the test.

there is an Assertion error that i tried my best to find a fix but utterly failed.

2016-09-19 00:01 UTC, barberboy commented
Hi, Matilda!

I think the only issue with this is that the `for` loop should start at 1 instead of 0. The rest of it looks good!

2016-09-19 10:15 UTC, barberboy commented on fizzbuzz.js
> +for(var i= 0;i <= 100; i++){
Per the assignment instructions, the `for` loop should start at 1 instead of 0.

2016-09-19 10:15 UTC, barberboy requested changes

2016-09-20 01:34 UTC, mkdev2015 commented
assignment completed with test passed

2016-09-21 18:05 UTC, barberboy approved these changes

2016-09-21 18:05 UTC, barberboy commented
This is great, Matilda! 👍  💯

2016-09-21 18:05 UTC, closed without merging